environment:
  matrix:
    - JAVA_HOME : C:\Program Files\Java\jdk1.6.0\
    - JAVA_HOME : C:\Program Files\Java\jdk1.7.0\
    - JAVA_HOME : C:\Program Files\Java\jdk1.8.0\

install:
  - cmd: java -version

test_script:
  - mvn verify javadoc:javadoc site:site

cache:
  - '%HOMEPATH%\.m2' 

build: off
